### ISSUE TITLE
NPE on shutdown

### ISSUE THREAD

**Issue by iloveeclipse** [briandealwis/ferret#81] opened 2017-10-25 21:30 UTC
Running Eclipse in Eclipse, if I start some Ferret unrelated JUnit tests, I see that NPE on shutdown of the test JVM:

```
!ENTRY ca.ubc.cs.ferret.jdt 4 0 2017-10-25 23:27:05.738
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in ca.ubc.cs.ferret.jdt.FerretJdtPlugin.stop() of bundle ca.ubc.cs.ferret.jdt.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:855)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:970)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:313)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1675)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1594)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:270)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:146)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:164)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementImageProvider.<init>(JavaElementImageProvider.java:79)
	at org.eclipse.jdt.ui.JavaElementLabelProvider.<init>(JavaElementLabelProvider.java:159)
	at ca.ubc.cs.ferret.jdt.JdtSphereHelper.start(JdtSphereHelper.java:61)
	at ca.ubc.cs.ferret.jdt.JdtSphereHelper.getDefault(JdtSphereHelper.java:54)
	at ca.ubc.cs.ferret.jdt.FerretJdtPlugin.stop(FerretJdtPlugin.java:37)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:835)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:828)
	... 13 more
Root exception:
java.lang.NullPointerException
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementImageProvider.<init>(JavaElementImageProvider.java:79)
	at org.eclipse.jdt.ui.JavaElementLabelProvider.<init>(JavaElementLabelProvider.java:159)
	at ca.ubc.cs.ferret.jdt.JdtSphereHelper.start(JdtSphereHelper.java:61)
	at ca.ubc.cs.ferret.jdt.JdtSphereHelper.getDefault(JdtSphereHelper.java:54)
	at ca.ubc.cs.ferret.jdt.FerretJdtPlugin.stop(FerretJdtPlugin.java:37)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:835)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:828)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:970)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:313)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1675)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1594)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:270)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:146)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:164)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by briandealwis** [comment] 2017-10-26 09:01
Duplicate of #50, fixed by #51 
Time for a new release!

**Closed as completed by briandealwis** 2017-10-26 09:01 UTC
Labels: bug
